### ISSUE TITLE
Tasks - Categorize tasks

### ISSUE THREAD

**Issue by gracekim15237** [CSC207-2022F-UofT/course-project-notty#7]
### Categorizing tasks
As a user, I want to categorize my tasks into sections, so that I can intuitively figure out if I have done things in each field.

**Description:**
- [ ] Create category
- [ ] Edit category
- [ ] Delete category

**Comment by tanmah2809** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/quickstart

**Comment by gracekim15237** [comment]
- [x] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:
